steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/api', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/api']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run',
    'deploy',
    'api',
    '--image', 'gcr.io/$PROJECT_ID/api',
    '--region', 'europe-west2',
    '--platform', 'managed',
    '--allow-unauthenticated'
  ]
images:
- gcr.io/$PROJECT_ID/api